### ISSUE TITLE
BUG: Endless loop in func HandlePDUSessionSMContextRelease

### ISSUE THREAD

**Issue by m3od5c** [free5gc/smf#4]
func HandlePDUSessionSMContextRelease(rspChan chan smf_message.HandlerResponseMessage, smContextRef string, body models.ReleaseSmContextRequest) (seqNum uint32) {
.
for curDataPathNode := dataPath.FirstDPNode; *curDataPathNode != nil*; **curDataPathNode.Next()** {
.

correct:
for curDataPathNode := dataPath.FirstDPNode; curDataPathNode != nil;  **curDataPathNode = curDataPathNode.Next()** {

**Comment by free5gc-org** [comment]
Yes, this is our bug.

How about giving a PR to fix this?

**Comment by free5gc-org** [comment]
This issue has been fixed by PR #5
