### ISSUE TITLE
Smf Event Exposure Subscription not respond event  report

### ISSUE THREAD

**Issue by Abbey-12** [free5gc/smf#78]
@brianchennn,

I'm currently working on integrating NWDAF with the free5g core. As part of this integration, I need to collect data from each network function component using the event exposure service of each NF. The issue I'm facing is that when I make a subscription to the SMF (Session Management Function), I receive a success code, but I don't receive any reports. I would greatly appreciate your assistance in resolving this issue. Thank you for your help.

 url = 'http://192.168.15.202:8009/nsmf_event-exposure/v1/subscriptions'
headers = {
    'accept': 'application/json',
    'Content-Type': 'application/json'
}

data = {
    "subscription": {
    "eventList": [
        {
            "type": "PDU_SESSION_ESTABLISHMENT ",
            "immediateFlag": True,
            "refId": 0
        }
    ],
    "notifUri": "http://192.168.15.202:5000/callback",
    "supi": "imsi-208930000000001",
    "gpsi": "string",
    "anyUeInd": False,
    "groupId": "string",
    "pduSeId": "string",
    "subId": "string",
    "notifId": "string",
    "ImmeRep": True,
    "notifMethod": "CONTINUOUS",
    "maxReportNbr": 30,
    "expiry": "2023-05-31T11:30:51Z",
    "repPeriod": 1,
    "guami": "string",
    "serviceName": "string",
    "supportedFeatures": "FFFF"
}
}

response = requests.post(url, headers=headers, data=json.dumps(data))

**Comment by ianchen0119** [comment]
Hi @Abbey-12 

Currently, We haven't plan to implement the event exposure feature on SMF.
As for your requirement, I think you can implement the custom metrics exporter.
Hope it be help to you.

Best Regards.
